const courseCatalog = [
  {
    slug: "digital-marketing-course",
    title: "Digital Marketing Masterclass",
    description:
      "Advanced digital marketing strategies, SEO, SEM, PPC, social media marketing, and analytics.",
    keywords: [
      "Digital Marketing Course",
      "SEO Course",
      "SEM Training",
      "PPC Course",
      "Social Media Marketing",
      "Digital Marketing Institute in Delhi",
    ],
    category: "Digital Marketing",
    level: "Advanced",
    duration: "16 Weeks",
    image: "/marketing.png",
    price: 60000,
    discountedPrice: 40000,
  },
  {
    slug: "full-stack-development-course",
    title: "Full Stack Web Development",
    description:
      "Master front-end (React) and back-end (Node.js) technologies to build complete web applications.",
    keywords: [
      "Full Stack Development Course",
      "Web Development Course",
      "React Course",
      "Node.js Course",
      "MERN Stack Training",
    ],
    category: "Web Development",
    level: "Intermediate",
    duration: "12 Weeks",
    image: "/full-stack.jpg",
    price: 60000,
    discountedPrice: 40000,
  },
  {
    slug: "data-analytics-course",
    title: "Data Analytics with Python and SQL",
    description:
      "Master data analysis with Python (Pandas, NumPy) and SQL. Learn visualization and reporting.",
    keywords: [
      "Data Analytics Course",
      "Python for Data Analysis",
      "SQL Training",
      "Data Visualization",
      "Business Analytics",
    ],
    category: "Data Science",
    level: "Intermediate",
    duration: "14 Weeks",
    image: "/data.jpg",
    price: 55000,
    discountedPrice: 38000,
  },
  {
    slug: "ui-design-course",
    title: "UI/UX Design Fundamentals",
    description:
      "Learn UI and UX design principles, layouts, wireframing, and prototyping with Figma.",
    keywords: [
      "UI UX Design Course",
      "Figma Course",
      "UI Design Training",
      "UX Fundamentals",
      "Product Design",
    ],
    category: "Design",
    level: "Beginner",
    duration: "8 Weeks",
    image: "/ui.jpg",
    price: 35000,
    discountedPrice: 25000,
  },
  {
    slug: "finance-course",
    title: "Finance Fundamentals",
    description:
      "Learn budgeting, saving, investing, and financial planning to build strong money skills.",
    keywords: [
      "Finance Course",
      "Personal Finance Training",
      "Investment Basics",
      "Budgeting Course",
      "Financial Planning",
    ],
    category: "Finance",
    level: "Beginner",
    duration: "8 Weeks",
    image: "/finance.jpg",
    price: 25000,
    discountedPrice: 16000,
  },
  {
    slug: "accounting-course",
    title: "Accounting Fundamentals",
    description:
      "Master accounting principles, financial statements, GST, and bookkeeping practices.",
    keywords: [
      "Accounting Course",
      "Tally Course",
      "GST Training",
      "Bookkeeping",
      "Accounting Institute in Delhi",
    ],
    category: "Accounting",
    level: "Beginner",
    duration: "12 Weeks",
    image: "/spanish-course.jpg",
    price: 45000,
    discountedPrice: 25000,
  },
  {
    slug: "android-development-course",
    title: "Android App Development",
    description:
      "Build native Android apps with modern tools, UI, and app architecture fundamentals.",
    keywords: [
      "Android Development Course",
      "Kotlin Training",
      "Android Studio",
      "Mobile App Development",
      "Firebase Basics",
    ],
    category: "Mobile Development",
    level: "Intermediate",
    duration: "10 Weeks",
    image: "/android.jpg",
    price: 45000,
    discountedPrice: 30000,
  },
  {
    slug: "basic-computer-course",
    title: "Basic Computer Skills",
    description:
      "Learn operating systems, file management, internet usage, and office applications.",
    keywords: [
      "Basic Computer Course",
      "Computer Fundamentals",
      "Microsoft Office Training",
      "Computer Basics",
    ],
    category: "Computer Basics",
    level: "Beginner",
    duration: "4 Weeks",
    image: "/computer-basic.jpg",
    price: 12999,
    discountedPrice: 7999,
  },
  {
    slug: "advance-computer-course",
    title: "Advanced Computer Applications",
    description:
      "Advance your skills with Excel, data management, automation, and productivity tools.",
    keywords: [
      "Advanced Computer Course",
      "Advanced Excel",
      "Data Management",
      "Office Automation",
    ],
    category: "Computer Applications",
    level: "Advanced",
    duration: "8 Weeks",
    image: "/computerc.jpg",
    price: 16999,
    discountedPrice: 11999,
  },
  {
    slug: "amazon-digital-marketing-course",
    title: "Amazon Digital Marketing and Ads",
    description:
      "Learn Amazon SEO, PPC sponsored ads, and ecommerce growth strategies.",
    keywords: [
      "Amazon Digital Marketing",
      "Amazon Ads Course",
      "Amazon SEO",
      "Ecommerce Marketing",
      "Amazon PPC",
    ],
    category: "Digital Marketing",
    level: "Intermediate",
    duration: "8 Weeks",
    image: "/amam.jpg",
    price: 35000,
    discountedPrice: 24000,
  },
  {
    slug: "english-speaking-course",
    title: "English Communication",
    description:
      "Improve professional English for meetings, presentations, emails, and interviews.",
    keywords: [
      "English Speaking Course",
      "Business English",
      "Communication Skills",
      "Spoken English",
      "English Training",
    ],
    category: "Language",
    level: "Intermediate",
    duration: "6 Weeks",
    image: "/english-course.jpg",
    price: 15000,
    discountedPrice: 9999,
  },
  {
    slug: "affiliate-marketing-course",
    title: "Affiliate Marketing and Lead Generation",
    description:
      "Learn affiliate marketing strategies, SEO, and content-driven lead generation.",
    keywords: [
      "Affiliate Marketing Course",
      "Lead Generation",
      "SEO Training",
      "Content Marketing",
      "Affiliate Programs",
    ],
    category: "Digital Marketing",
    level: "Intermediate",
    duration: "6 Weeks",
    image: "/affiliate.png",
    price: 70000,
    discountedPrice: 35000,
  },
  {
    slug: "youtube-seo-growth-course",
    title: "YouTube SEO and Channel Growth",
    description:
      "Master YouTube SEO, content strategy, and monetization to grow a channel.",
    keywords: [
      "YouTube SEO Course",
      "YouTube Growth",
      "Video Marketing",
      "Content Strategy",
      "YouTube Monetization",
    ],
    category: "Digital Marketing",
    level: "Intermediate",
    duration: "10 Weeks",
    image: "/computerc.jpg",
    price: 15000,
    discountedPrice: 20000,
  },
  {
    slug: "web-development-course",
    title: "Web Development Course",
    description:
      "Build modern websites and web apps with core frontend and backend fundamentals.",
    keywords: [
      "Web Development Course",
      "Frontend Development",
      "Backend Development",
      "HTML CSS JavaScript",
    ],
    category: "Web Development",
    level: "Beginner",
    duration: "12 Weeks",
    image: "/full-stack.jpg",
    price: 55000,
    discountedPrice: 35000,
  },
  {
    slug: "job-training-course",
    title: "Job Training Program",
    description:
      "Career-focused training with interview prep, resume support, and placement assistance.",
    keywords: [
      "Job Training",
      "Career Preparation",
      "Resume Building",
      "Placement Assistance",
    ],
    category: "Career",
    level: "Beginner",
    duration: "6 Weeks",
    image: "/default-course-image.png",
    price: 20000,
    discountedPrice: 12000,
  },
]

const getCourseBySlug = (slug) => courseCatalog.find((course) => course.slug === slug)

export { courseCatalog, getCourseBySlug }
